name: ipty build test

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: daisukebtw
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build Docker image
        run: |
          VERSION="1.${{ github.run_number }}"
          docker build -t daisukebtw/ipty-api:$VERSION ./api
          docker build -t daiuskebtw/ipty-app:$VERSION ./app
      
      - name: Push Docker image
        run: |
          docker push daisukebtw/ipty-api:$VERSION
          docker push daisukebtw/ipty-app:$VERSION


      - name: Checkout configuration repository
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.K8S_CONFIG_REPO }}
          token: ${{ secrets.K8S_CONFIG_REPO_TOKEN }}
          ref: main

      - name: Update API and APP Kubernetes manifest
        run: |
          API_MANIFEST_FILE=api-ipty-deployment.yaml
          APP_MANIFEST_FILE=app-ipty-deployment.yaml
          sed -i "s|image: .*|image: ipty-api:$VERSION|" $API_MANIFEST_FILE
          sed -i "s|image: .*|image: ipty-app:$VERSION|" $APP_MANIFEST_FILE
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add $API_MANIFEST_FILE $APP_MANIFEST_FILE
          git commit -m "Update Docker image versions"

      - name: Push changes
        run: git push


