name: ipty build test

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  api-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Python API
        uses: |
          pip3 install -r api/requirements.txt
          python3 api/api.py & sleep 10

  app-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build TypeScript APP
        uses: |
          cd app/ && npm install
          npm run build
