name: ipty build test

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      API_IMAGE_NAME: ipty-api
      APP_IMAGE_NAME: ipty-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: daisukebtw
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Set VERSION variable
        run: |
          VERSION=1.${{ github.run_number }}
          echo "VERSION=1.${{ github.run_number }}" >> $GITHUB_ENV

      
      - name: Build API Docker image
        run: |
          docker build -t daisukebtw/$APP_IMAGE_NAME:$VERSION ./app
          docker build -t daisukebtw/$API_IMAGE_NAME:$VERSION ./api

      
      - name: Push Docker image
        run: |
          docker push daisukebtw/$API_IMAGE_NAME:$VERSION
          docker push daisukebtw/$APP_IMAGE_NAME:$VERSION


      - name: Checkout configuration repository
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.K8S_CONFIG_REPO }}
          token: ${{ secrets.K8S_CONFIG_REPO_TOKEN }}
          ref: main

      - name: Update API and APP Kubernetes manifest
        run: |
          API_MANIFEST_FILE=api-ipty-deployment.yaml
          APP_MANIFEST_FILE=app-ipty-deployment.yaml
          sed -i "s|image: .*|image: $API_IMAGE_NAME:$VERSION|" $API_MANIFEST_FILE
          sed -i "s|image: .*|image: $APP_IMAGE_NAME:$VERSION|" $APP_MANIFEST_FILE
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add $API_MANIFEST_FILE $APP_MANIFEST_FILE
          git commit -m "Update Docker image versions"

      - name: Push changes
        run: git push


